CREATE TABLE Customers (
	Id INT PRIMARY KEY CLUSTERED NOT NULL IDENTITY(1, 1),
	Email NVARCHAR(256) NOT NULL UNIQUE,
	Name NVARCHAR(256) NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL,
	IsActive BIT NOT NULL,
	Latitude FLOAT NULL,
	Longitude FLOAT NULL
)
GO
